import ".common-rust.justfile"

import? '.justfile.local'

mod web
mod api
mod docker
mod doc

[private]
default:
    @just --choose

## Environment info
print-env-info:
    #!/usr/bin/env bash
    echo "╭──────────────────────────────────────────────────────────────╮"
    echo "│              Universal Inbox Environment Info                │"
    echo "╰──────────────────────────────────────────────────────────────╯"
    echo ""
    echo "🌐 Web UI:           http://localhost:${DX_SERVE_PORT:-8080}"
    echo "🔌 API:              http://localhost:${API_PORT:-8000}"
    echo "🐘 PostgreSQL:       postgres://postgres:password@127.0.0.1:${PGPORT:-5432}/universal-inbox"
    echo "📮 Redis:            redis://127.0.0.1:${REDIS_PORT:-6379}"

## Setup recipes
init-db:
  #!/usr/bin/env bash
  set -euo pipefail

  data_dir=.devbox/virtenv/postgresql_17/data

  [ -f "$data_dir/postgresql.conf" ] \
    || initdb -D "$data_dir" --username=postgres --pwfile=<(echo password)

  # Tuning for a *disposable* cluster. This one holds nothing but development and test data,
  # so trading crash durability for speed is free: `fsync=off` alone removes one disk flush per
  # commit, and the test suite commits constantly. Never apply this to a cluster whose contents
  # you would miss. Written to a separate file and `include`d so `postgresql.conf` stays the
  # stock one initdb produced.
  cat > "$data_dir/postgresql.universal-inbox.conf" <<'CONF'
  # Generated by `just init-db` — see the recipe for why these are safe here.
  fsync = off
  synchronous_commit = off
  full_page_writes = off
  max_wal_size = 4GB
  checkpoint_timeout = 3600
  # Each test process opens its own pool, so the cluster sees test-threads x max_connections.
  max_connections = 200
  shared_buffers = 256MB
  CONF

  grep -q "postgresql.universal-inbox.conf" "$data_dir/postgresql.conf" \
    || echo "include = 'postgresql.universal-inbox.conf'" >> "$data_dir/postgresql.conf"

install-rust-toolchain:
  #!/usr/bin/env bash

  rustup show active-toolchain | grep -q "^$RUST_TOOLCHAIN_VERSION-" || rustup default $RUST_TOOLCHAIN_VERSION
  active=$(rustup show active-toolchain | awk '{ print $1 }')
  for toolchain in $(rustup toolchain list | grep -v "$active" | grep -vE '^(nightly|beta|stable)'); do
    rustup toolchain uninstall $toolchain
  done
  rustup target list --installed | grep -q '^wasm32-unknown-unknown$' || rustup target add wasm32-unknown-unknown
  rustup component list --installed | grep -q '^rust-analyzer-' || rustup component add rust-analyzer
  rustup component list --installed | grep -q '^llvm-tools-' || rustup component add llvm-tools-preview

install-tools:
  #!/usr/bin/env bash

  if [ -z "$DOCKER_BUILD" ]; then
    cargo binstall -y cargo-llvm-cov --version 0.6.16
  fi
  just api install-tools

## Build recipes
build-release-all: build-release
    just web build-release
    just api build-release

## Dev recipes
check-all: check
    just web check
    just api check

format-all:
    cargo fmt --all

check-format:
    cargo fmt --all --check

lint-dockerfile:
    hadolint Dockerfile

@check-commit:
    env SKIP= prek run -a

## Test recipes
test-all: test
    just web test
    just api test

## Run recipes
@create-docker-network:
    #!/usr/bin/env bash
    docker network ls | awk '{print $2}' | grep -q '^universal-inbox$' \
        || docker network create universal-inbox;

run:
    #!/usr/bin/env bash
    PC_PORT=${PROCESS_COMPOSE_PORT:-9999}
    if process-compose -p "$PC_PORT" process list >/dev/null 2>&1; then
        exec process-compose -p "$PC_PORT" attach
    fi
    exec process-compose \
        -f .devbox/virtenv/redis/process-compose.yaml \
        -f process-compose-pg.yaml \
        -f process-compose.yaml \
        -p "$PC_PORT"

# Start the stack detached + headless (no TUI) — for agents / CI / non-interactive shells.
# Brings up postgresql + redis; app services (ui-*) stay disabled, start them with `just start`.
# Idempotent: a no-op if the stack is already running on this port. Tear down with `just down`.
run-detached:
    #!/usr/bin/env bash
    PC_PORT=${PROCESS_COMPOSE_PORT:-9999}
    if process-compose -p "$PC_PORT" process list >/dev/null 2>&1; then
        echo "process-compose already running on port $PC_PORT"
        exit 0
    fi
    process-compose \
        -f .devbox/virtenv/redis/process-compose.yaml \
        -f process-compose-pg.yaml \
        -f process-compose.yaml \
        -p "$PC_PORT" up -D -t=false

# Stop the detached stack started by `run-detached`.
@down:
    process-compose -p ${PROCESS_COMPOSE_PORT:-9999} down

@start service:
    process-compose -p ${PROCESS_COMPOSE_PORT:-9999} process start {{ service }}

@stop service:
    process-compose -p ${PROCESS_COMPOSE_PORT:-9999} process stop {{ service }}

@logs service:
    process-compose -p ${PROCESS_COMPOSE_PORT:-9999} process logs -n 100 -f {{ service }}

status:
    #!/usr/bin/env bash
    PC_PORT=${PROCESS_COMPOSE_PORT:-9999}
    echo "╭──────────────────────────────────────────────────────────────╮"
    echo "│                    Service Status                            │"
    echo "╰──────────────────────────────────────────────────────────────╯"
    echo ""
    for service in postgresql redis ui-api ui-workers ui-web; do
        json=$(process-compose -p $PC_PORT process get -o json "$service" 2>/dev/null)
        status=$(echo "$json" | jq -r '.[0].status // "Unknown"')
        is_running=$(echo "$json" | jq -r '.[0].is_running // false')
        if [ "$is_running" = "true" ]; then
            icon="✅"
        elif [ "$status" = "Disabled" ]; then
            icon="⏸️ "
        else
            icon="❌"
        fi
        printf "%s %-15s %s\n" "$icon" "$service" "$status"
    done

open:
    open "http://localhost:${DX_SERVE_PORT:-8000}"
