[package]
name = "universal-inbox"
version = "0.1.0"
edition = "2021"
authors = ["David Rousselie <david@universal-inbox.com>"]

[workspace]
members = ["api", "web"]

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.8.0", features = ["serde"] }
chrono = { version = "0.4.0", features = ["serde"] }
enum_derive = "0.1.0"
macro-attr = "0.2.0"
serde_with = "1.14.0"
http = "0.2.0"
git-url-parse = { git = "https://github.com/dax/git-url-parse-rs", rev = "5561f3c4e044207d6be0fdb03aa0f6b75f5bc9c8" }
