[package]
name = "universal-inbox"
version.workspace = true
edition.workspace = true
authors.workspace = true

[workspace]
members = ["api", "web"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["David Rousselie <david@universal-inbox.com>"]

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
chrono = { workspace = true, features = ["serde"] }
enum_derive = { workspace = true }
git-url-parse = "0.4.0"
http = { workspace = true }
macro-attr = { workspace = true }
num_enum = "0.5.0"
serde = { workspace = true }
serde_json = { workspace = true, features = ["preserve_order"] }
serde_repr = "0.1.0"
serde_with = { workspace = true }
url = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["serde"] }

[workspace.dependencies]
anyhow = { version = "1.0" }
chrono = { version = "0.4.0", default-features = false, features = [
  "clock",
  "std",
] }
enum_derive = { version = "0.1.0" }
http = { version = "0.2.0" }
lazy_static = { version = "1.4.0" }
log = { version = "0.4.0" }
macro-attr = { version = "0.2.0" }
openidconnect = { version = "3.0.0-alpha.1" }
pretty_assertions = { version = "1.3.0" }
reqwest = { version = "0.11", features = ["json", "cookies"] }
rstest = { version = "0.13.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
serde_with = { version = "2.3.0" }
thiserror = { version = "1.0" }
url = { version = "2.3.0" }
uuid = { version = "1.0", features = ["v4"] }

[patch.crates-io]
# Patch Dioxus to access use_memo, use_effect seems buggy as of 0.3.1
dioxus = { git = "https://github.com/DioxusLabs/dioxus.git", rev = "9a053a0b51b1f38a190c4e9a56b32e0f667301c8" }
dioxus-core = { git = "https://github.com/DioxusLabs/dioxus.git", rev = "9a053a0b51b1f38a190c4e9a56b32e0f667301c8" }
dioxus-hooks = { git = "https://github.com/DioxusLabs/dioxus.git", rev = "9a053a0b51b1f38a190c4e9a56b32e0f667301c8" }
dioxus-html = { git = "https://github.com/DioxusLabs/dioxus.git", rev = "9a053a0b51b1f38a190c4e9a56b32e0f667301c8" }
dioxus-router = { git = "https://github.com/DioxusLabs/dioxus.git", rev = "9a053a0b51b1f38a190c4e9a56b32e0f667301c8" }
dioxus-web = { git = "https://github.com/DioxusLabs/dioxus.git", rev = "9a053a0b51b1f38a190c4e9a56b32e0f667301c8" }
fermi = { git = "https://github.com/DioxusLabs/dioxus.git", rev = "9a053a0b51b1f38a190c4e9a56b32e0f667301c8" }

[dev-dependencies]
pretty_assertions = { workspace = true }
rstest = { workspace = true }
