version: "0.6"

processes:
  ui-api:
    command: "just api run-api"
    depends_on:
      postgresql:
        condition: process_started
      redis:
        condition: process_started
    availability:
      restart: no
    disabled: true
    namespace: "universal-inbox"

  ui-workers:
    command: "just api run-workers"
    depends_on:
      postgresql:
        condition: process_started
      redis:
        condition: process_started
    availability:
      restart: no
    disabled: true
    namespace: "universal-inbox"

  ui-web:
    command: "just web run"
    availability:
      restart: no
    is_tty: true
    disabled: true
    namespace: "universal-inbox"

  build-tailwind:
    command: "just web run-tailwind"
    is_tty: true
    disabled: true
    namespace: "universal-inbox"

  bundle-js:
    command: "just web run-bundle-js"
    is_tty: true
    disabled: true
    namespace: "universal-inbox"

  nango-db:
    command: "just run-nango-db"
    shutdown:
      command: "docker stop nango-db"
    disabled: true
    namespace: "nango"

  nango-server:
    command: "just run-nango-server"
    shutdown:
      command: "docker stop nango-server"
    depends_on:
      nango-db:
        condition: process_started
    disabled: true
    namespace: "nango"

  caddy:
    command: "caddy run --config=$CADDY_CONFIG"
    is_tty: true
    disabled: true
    availability:
      restart: on_failure
      max_restarts: 5
