version: "0.6"

processes:
  postgresql:
    command: "pg_ctl start -o \"-k '$PGHOST'\""
    is_daemon: true
    shutdown:
      command: "pg_ctl stop -m fast"
    availability:
      restart: "always"
    readiness_probe:
      exec:
        command: "pg_isready"
