window.UI_DATA = {
  integrations: [
    { id: "github",  name: "GitHub",       icon: "logos:github-icon",     color: null, status: "ok" },
    { id: "linear",  name: "Linear",       icon: "logos:linear-icon",     color: null, status: "ok" },
    { id: "slack",   name: "Slack",        icon: "logos:slack-icon",      color: null, status: "error" },
    { id: "gmail",   name: "Google Mail",  icon: "logos:google-gmail",    color: null, status: "ok" },
    { id: "gcal",    name: "Calendar",     icon: "logos:google-calendar", color: null, status: "ok" },
    { id: "todoist", name: "Todoist",      icon: "logos:todoist-icon",    color: null, status: "ok" },
    { id: "notion",  name: "Notion",       icon: "logos:notion-icon",     color: null, status: "ok" },
  ],
  notifications: [
    {
      id: "n1", source: "github", when: "12m", group: "Today",
      title: "feat: Add OAuth2 PKCE flow for Linear integration #142",
      repo: "universal-inbox/api",
      actor: "david.rousselie",
      tag: { kind: "review", label: "review" },
      unread: true, mention: true,
      body: "Adds a Proof-Key-for-Code-Exchange flow on the Linear OAuth handshake, so the desktop client no longer needs to store a client secret.\n\n— Moves `linear_oauth.rs` to use the `oauth2` crate PKCE helpers\n— Updates the token-refresh background worker\n— Adds integration tests against the Linear staging API",
      meta: [["author","david.rousselie"],["branch","feat/linear-pkce"],["checks","4 passing"]],
    },
    {
      id: "n2", source: "linear", when: "34m", group: "Today",
      title: "Implement notification grouping by source",
      repo: "UI-2847",
      actor: "Clara Merz",
      tag: { kind: "urgent", label: "urgent" },
      unread: true,
      body: "Users have asked for the ability to collapse notifications by source when the list gets long. Designs attached — this is the last blocker for the v2.4 release.",
      meta: [["assignee","you"],["status","In Progress"],["priority","Urgent"]],
    },
    {
      id: "n3", source: "slack", when: "1h", group: "Today",
      title: "@marc mentioned you in #engineering",
      repo: "#engineering",
      actor: "Marc Antoine",
      tag: null,
      unread: true, mention: true,
      body: "Hey, can you take a look at the PKCE PR when you get a minute? Trying to get it in before the 4pm ship meeting. 📥 Universal Inbox new release 📥",
      meta: [["channel","#engineering"],["reactions","3"]],
    },
    {
      id: "n4", source: "github", when: "2h", group: "Today",
      title: "fix: Stabilize browser tests with shared Playwright #130",
      repo: "universal-inbox/api",
      actor: "mkt-bot",
      tag: { kind: "merged", label: "merged" },
      body: "Shares a single Playwright browser instance across test files, cutting CI time from 8m to 2m40s.",
      meta: [["author","mkt-bot"],["merged by","david.rousselie"]],
    },
    {
      id: "n5", source: "gcal", when: "3h", group: "Today",
      title: "Design sync — Weekly",
      repo: "Tomorrow · 10:00",
      actor: "Calendar",
      tag: null,
      body: "Weekly design review with the product team. Agenda in the Notion doc.\n\nParticipants: 6 accepted, 1 tentative.",
      meta: [["when","Tomorrow 10:00 – 10:45"],["location","Zoom"],["organizer","Clara Merz"]],
    },
    {
      id: "n6", source: "gmail", when: "Yesterday", group: "Yesterday",
      title: "Your invoice from Linear is ready",
      repo: "billing@linear.app",
      actor: "Linear Billing",
      tag: null,
      body: "Invoice #INV-2894-1 for October 2025 is attached. Total due: €48.00. No action required — auto-paid via card ending 4242.",
      meta: [["from","billing@linear.app"],["amount","€48.00"]],
    },
    {
      id: "n7", source: "notion", when: "Yesterday", group: "Yesterday",
      title: "Q1 Planning doc — shared with you",
      repo: "Product / Planning",
      actor: "Clara Merz",
      tag: null,
      body: "Clara shared a Notion doc with you. Review before Friday's planning session.",
      meta: [["shared by","Clara Merz"],["workspace","Universal Inbox"]],
    },
    {
      id: "n8", source: "todoist", when: "2 days", group: "Earlier",
      title: "Task: Review OSS contributor guidelines",
      repo: "Inbox",
      actor: "Todoist",
      tag: null,
      body: "Reminder from Todoist — due today. Linked from GitHub issue #87.",
      meta: [["project","Inbox"],["due","Today"]],
    },
  ],
};
