[pre-start]
copy = "wt step copy-ignored"
clean_data = "rm -rf .devbox/virtenv/redis .devbox/virtenv/postgresql_17/data"
fix_permissions = "chmod -R og-rwx .devbox/virtenv/postgresql_17"
env = """
cat >> .local_envrc << EOF
export PGPORT={{ ('db-' ~ branch) | hash_port }}
export REDIS_PORT={{ ('redis-' ~ branch) | hash_port }}
export DX_SERVE_PORT={{ ('web-' ~ branch) | hash_port }}
export API_PORT={{ ('api-' ~ branch) | hash_port }}
export PROCESS_COMPOSE_PORT={{ ('pc-' ~ branch) | hash_port }}

export DATABASE_URL="postgres://postgres:password@127.0.0.1:{{ ('db-' ~ branch) | hash_port }}/universal-inbox"
export UNIVERSAL_INBOX__DATABASE__PORT={{ ('db-' ~ branch) | hash_port }}
export UNIVERSAL_INBOX__REDIS__PORT={{ ('redis-' ~ branch) | hash_port }}
export UNIVERSAL_INBOX__APPLICATION__FRONT_BASE_URL=http://localhost:{{ ('web-' ~ branch) | hash_port }}
export UNIVERSAL_INBOX__APPLICATION__LISTEN_PORT={{ ('api-' ~ branch) | hash_port }}

# default PGHOST can became too long
export PGHOST=/tmp
EOF
"""
setup = "direnv allow"
web_install = "cd web && npm install"

[pre-remove]
stop_services = "direnv exec . process-compose down -p ${PROCESS_COMPOSE_PORT:-9999} || true"

[pre-commit]
check = "just check-commit"

[list]
url = "http://localhost:{{ ('web-' ~ branch) | hash_port }}"
api_url = "http://localhost:{{ ('api-' ~ branch) | hash_port }}"
db_url = "postgres://postgres:password@127.0.0.1:{{ ('db-' ~ branch) | hash_port }}/universal-inbox"
