[application]
environment = "dev"
listen_address = "127.0.0.1"
static_dir = "../web/dist"
min_sync_tasks_interval_in_minutes = 0
min_sync_notifications_interval_in_minutes = 0

[application.observability.logging]
log_directive = "info,universal_inbox_api=debug,sqlx=debug,lettre=debug"
dependencies_log_level = "info"

[application.http_session]
secret_key = "1234567890ABCDEF1234567890ABCDEF1234567890ABCDEF1234567890ABCDEF"
