pub mod email_verification_page;
pub mod login_page;
pub mod notifications_page;
pub mod page_not_found;
#[cfg(feature = "web")]
pub mod passkey_login_page;
#[cfg(feature = "web")]
pub mod passkey_signup_page;
pub mod password_reset_page;
pub mod password_update_page;
pub mod settings_page;
pub mod signup_page;
pub mod synced_tasks_page;
pub mod user_profile_page;
