extend = "../Makefile.toml"

[tasks.run]
clear = true
install_crate = { crate_name = "bunyan", binary = "bunyan" }
env = { "TASKRC" = "$PWD/taskrc" }
command = "bash"
args = ["-c", "cargo run | bunyan"]
