[application]
name = "universal-inbox"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "Universal Inbox | take control of your notifications, seamlessly manage tasks"

[web.resource]
image = ["images/favicon.ico"]

[web.resource.dev]

[web.watcher]
# when watcher trigger, regenerate the `index.html`
reload_html = true
# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]

[web.wasm_opt]
level = "0"
debug = true

[[web.proxy]]
backend = "http://localhost:8000/api/"
