extend = "../Makefile.toml"

[tasks.build-release]
install_script = '''
which trunk > /dev/null || cargo install trunk
npm install --dev
'''
command = "trunk"
args = ["build", "--release"]

[tasks.run]
clear = true
install_script = '''
which trunk > /dev/null || cargo install trunk
npm install --dev
'''
command = "trunk"
args = ["serve"]
