extend = "../Makefile.toml"

[tasks.build-release]
install_script = '''
which trunk > /dev/null || cargo install trunk
npm install --dev
'''
command = "trunk"
args = ["build", "--release"]

[tasks.run]
clear = true
install_script = '''
which trunk > /dev/null || cargo install trunk
npm install --dev
'''
command = "trunk"
args = ["serve"]

[tasks.test]
install_script = '''
which wasm-bindgen-test-runner > /dev/null || cargo install wasm-bindgen-cli
'''
command = "cargo"
args = ["test"]
